# Generated by Django 4.2.11 on 2026-05-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_event_guest_event_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by_identity',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
