# Generated by Django 4.2.11 on 2026-05-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_by_identity_event_created_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='difficulty',
        ),
    ]
